version: '2'

networks:
  test.local:

services:
  tier1a:
    build: tier1a/
    ports:
        - "60080:80"
        - "60443:443"
    environment:
        - PREFIX=tier1a
    volumes:
        - .:/scenario:ro
        - ../../../:/thruk:ro
    networks:
      test.local:
        aliases:
          - tier1a.test.local

  tier1b:
    build: tier1b/
    ports:
        - "60081:80"
        - "60444:443"
    environment:
        - PREFIX=tier1b
    volumes:
        - .:/scenario:ro
    networks:
      test.local:
        aliases:
          - tier1b.test.local

  tier1c:
    build: tier1c/
    ports:
        - "60082:80"
        - "60445:443"
    environment:
        - PREFIX=tier1c
    volumes:
        - .:/scenario:ro
    networks:
      test.local:
        aliases:
          - tier1c.test.local

  tier2a:
    build: tier2a/
    environment:
        - PREFIX=tier2a
    volumes:
        - .:/scenario:ro
        - ../../../:/thruk:ro
    networks:
      test.local:
        aliases:
          - tier2a.test.local
  tier2b:
    build: tier2b/
    environment:
        - PREFIX=tier2b
    volumes:
        - .:/scenario:ro
    networks:
      test.local:
        aliases:
          - tier2b.test.local
  tier2c:
    build: tier2c/
    environment:
        - PREFIX=tier2c
    volumes:
        - .:/scenario:ro
    networks:
      test.local:
        aliases:
          - tier2c.test.local


  tier3a:
    build: tier3a/
    environment:
        - PREFIX=tier3a
    volumes:
        - .:/scenario:ro
        - ../../../:/thruk:ro
    networks:
      test.local:
        aliases:
          - tier3a.test.local
  tier3b:
    build: tier3b/
    environment:
        - PREFIX=tier3b
    volumes:
        - .:/scenario:ro
        - ../../../:/thruk:ro
    networks:
      test.local:
        aliases:
          - tier3b.test.local

  krb5:
    build: krb5/
    networks:
      test.local:
        aliases:
          - krb5.test.local
