- yum:
    name:
      - perl-Test-Harness
      - perl-ExtUtils-Manifest
      - perl-ExtUtils-Install
    state: present
- lineinfile:
    path: /etc/locale.conf
    regexp: '^LANG='
    line: 'LANG=C.utf8'
