---
- hosts: all
  roles:
    - role: common
    - role: local_tests
    - role: thruk_developer
  tasks:
  - shell: omd config demo set APACHE_MODE own
  - shell: omd config demo set CORE none
  - shell: omd config demo set PNP4NAGIOS off
  - name: copy thruk_local.conf
    copy:
      src: /root/thruk_local.conf
      dest: /omd/sites/demo/etc/thruk/thruk_local.conf
      mode: 0644
      owner: demo
