version: "2"

services:
  omd:
    build: omd/
    ports:
        - "60080:80"
        - "60557:6557"
    #uncomment to enable strace in the container
    #cap_add:
    #    - SYS_PTRACE
    environment:
        - TZ=Europe/Berlin
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - ../../../:/thruk:ro
        - .:/test:ro
        - ./results:/work:rw
