site:
    build: omd/
    ports:
        - 60080:80
        - 60443:443
    environment:
        - TZ=Europe/Berlin
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - ../../../:/thruk:ro
        - ./:/test:ro
